name: ATtiny Firmware
on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        board:
          - fqbn: Dasduino_Boards:megaavr:easyc:chip=404
      fail-fast: false
      
    steps:
      - name: Checkout dev branch
        uses: actions/checkout@v2

      - run: echo ${{ matrix.board.fqbn }}

      - name: Attiny FW Test
        uses: arduino/compile-sketches@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          platforms: |
            - source-url: https://github.com/SolderedElectronics/Dasduino-Board-Definitions-for-Arduino-IDE/raw/master/package_Dasduino_Boards_index.json
              name: "Dasduino_Boards:megaavr"

          fqbn: ${{ matrix.board.fqbn }}
          libraries: |
            - source-path: ./
          sketch-paths: |
            - ./extras/attiny_firmware/
